# Generated by Django 3.0.2 on 2020-01-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='debt status', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='debt',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='debt.DebtCategories'),
        ),
        migrations.AlterField(
            model_name='debtcategories',
            name='category',
            field=models.CharField(default='debt category', max_length=50),
        ),
        migrations.AddField(
            model_name='debt',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='debt.DebtStatuses'),
        ),
    ]
