# Generated by Django 3.0.2 on 2020-01-11 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debt', '0002_auto_20200111_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debt',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myDebts', to=settings.AUTH_USER_MODEL),
        ),
    ]
