# Generated by Django 3.0.2 on 2020-01-12 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debt', '0003_auto_20200111_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UsersToDebt',
        ),
    ]
